export const CLIENT_URL = process.env.REACT_APP_CLIENT_URL;
export const SERVER_URL = process.env.REACT_APP_SERVER_URL;
export const USER_IMAGE_URL = SERVER_URL + "/images/users/";
export const TOUR_IMAGE_URL = SERVER_URL + "/images/tours/";
export const AUTH_URL = "/api/v1/auth";
export const USERS_URL = "/api/v1/users";
export const TOURS_URL = "/api/v1/tours";
export const REVIEWS_URL = "/api/v1/reviews";
export const BOOKINGS_URL = "/api/v1/bookings";
